### ISSUE TITLE
Tempoary file creation issues on Windows blocking download

### ISSUE THREAD

**Issue by Eluvias** [eddelbuettel/td#1]
The download of equity/etf securities fails while FX succeeds. Is this Windows specific or  user's settings?

``` r
# WORKS OK
eurusd <- td::time_series(sym="EUR/USD", interval="1week", as="xts", outputsize = 5)

# FAILS
spy <- td::time_series(sym="spy", interval="1week", as="xts", outputsize = 5)
#> Error in download.file(url = .url, destfile = .destfile, method = .method, : cannot open destfile
#> 'C:\Users\Eluvias\AppData\Local\Temp\RtmpqwABRW\time_series?symbol=spy&interval=1week&apikey=<API KEY HERE>&outputsize=56e4571310bd', reason 'Invalid argument'

# R version 4.0.3 (2020-10-10)
# Platform: x86_64-w64-mingw32/x64 (64-bit)
# Running under: Windows 10 x64 (build 19042)

# td  0.0.1.1 2021-02-14 [1] Github (eddelbuettel/td@4af421c)
```

If it helps the error is invoked in `RcppSimdJson:::.prep_input()` while creating the temp_files and passed into 
the `download.file()`,  e.g., 

``` r
temp_files[diagnosis$is_from_url] <- tempfile(pattern = .drop_file_ext(basename(diagnosis$input[diagnosis$is_from_url]), 
            diagnosis$file_ext[diagnosis$is_from_url]), tmpdir = normalizePath(temp_dir), 
            fileext = .fileext[diagnosis$is_from_url])
```

I noticed that a random alphanumeric is appended in the input url: "...&outputsize=56e4571310bd" instead of "...&outputsize=5"
but the download didn't fail for FX.

Thanks for the package. 😃

**Comment by eddelbuettel** [comment]
Try uppercase 'SPY'.  

I have been using ETFs all along here.

**Comment by Eluvias** [comment]
I had and didn't work. Actually, I had tried first the examples in README and then used some ETF symbols to see where is the problem. Have you or anyone else tried on Windows? The urls are constructed correctly, the error is raised in `RcppSimdJson::fload(qry)` and specifically in `RcppSimdJson:::.prep_input()`.

**Comment by Eluvias** [comment]
Here is another one:
```r
xx <- td::time_series(sym = "EEM", interval = "1day", as = "xts",outputsize = 5)
Error in download.file(url = .url, destfile = .destfile, method = .method,  : 
  cannot open destfile 'C:\Users\Constantine\AppData\Local\Temp\RtmpwJQghU\time_series?symbol=EEM&interval=1day&apikey=<API>&outputsize=53e38516a1b1b', reason 'Invalid argument'

```

**Comment by eddelbuettel** [comment]
That could be and in that case you raised an issue at the wrong repo :)  It would then be a problem for @knapply and me in repo [RcppSimdJson](https://github.com/eddelbuettel/rcppsimdjson).

We should be able to help you there.  Can you be as specific as possible on the error?  What you quote above, _i.e._ 

```r
# FAILS
spy <- td::time_series(sym="spy", interval="1week", as="xts", outputsize = 5)
#> Error in download.file(url = .url, destfile = .destfile, method = .method, : cannot open destfile
#> 'C:\Users\Eluvias\AppData\Local\Temp\RtmpqwABRW\time_series?symbol=spy&interval=1week&apikey=<API KEY HERE>&outputsize=56e4571310bd', reason 'Invalid argument'
```

is entirely *local*.  Please try to follow the path by hand and see if you can open a file with `.destfile` path, and if you cannot, which variation of `.destfile` would.

**Comment by eddelbuettel** [comment]
>  and specifically in `RcppSimdJson:::.prep_input()`.

Can you show that?

**Comment by Eluvias** [comment]
> Can you show that?

Yes. I will open an issue in RcppSimdJson repo with reproducible example.

**Comment by Eluvias** [comment]
With dev version or [RcppSimdJson](https://github.com/eddelbuettel/rcppsimdjson) :
``` r
td::time_series(sym=c("EEM", "EUR/USD", "SPY"), interval="1week", as="xts", outputsize = 1)

#> $EEM
#>              open   high    low close    volume
#> 2021-02-08 56.042 57.995 56.042 57.79 146541543
#> 
#> $`EUR/USD`
#>             open   high     low   close
#> 2021-02-08 1.204 1.2149 1.20195 1.21205
#> 
#> $SPY
#>              open  high   low  close    volume
#> 2021-02-08 389.27 392.9 387.5 392.69 199929918
```

**Comment by eddelbuettel** [comment]
I'll close this but will add a note to the README.md to this effect.
