### ISSUE TITLE
R version check on installation for R < 4.0.0

### ISSUE THREAD

**Issue by mdequeljoe** [eddelbuettel/td#2]
Hi Dirk, 

Thanks for this useful package. It is also great to see that it is recommended by twelvedata. 

I just noticed an issue when installing the package from CRAN using an R version < 4.0.0

```R
R.version.string
#> [1] "R version 3.6.1 (2019-07-05)"

install.packages('td')
#> installing the source package ‘td’
#> ...
#> Error: package or namespace load failed for #> ‘td’:
#>  .onLoad failed in loadNamespace() for 'td', details:
#>   call: NULL
#>   error: 'R_user_dir' is not an exported object from 'namespace:tools'
#> Error: loading failed
#> Execution halted
```

Which comes from:

https://github.com/eddelbuettel/td/blob/48cbf97a73f21d27718d99d23e0604f725e6b708/R/init.R#L22-L24

as we have in this case:

```R
R.version.string >= "4.0.0"
#> TRUE
```

So one may want to use `getRversion` instead:

```R
getRversion() >= "4.0.0"
#> FALSE
```

which would lead to the following change:

```R
.defaultFile <- function() {
    if (getRversion() >= "4.0.0") {
        tddir <- tools::R_user_dir("td")
        if (dir.exists(tddir)) {
            fname <- file.path(tddir, "api.dcf")
            if (file.exists(fname)) {
                return(fname)
            }
        }
    }
    return("")
}
```

**Comment by eddelbuettel** [comment]
I would recommend you make that change locally.  R 4.0.0 is now a year old, and we will have R 4.1.0 next week,

**Comment by eddelbuettel** [comment]
But you have a point that the requirement should be explicit. I'll add that to the DESCRIPTION files as a versioned depends in which case the code can remain as is.

**Comment by eddelbuettel** [comment]
I uploaded a new version 0.0.3 with a more explicit dependency on R (>= 4.0.0) -- but the better fix is

```diff
modified   R/init.R
@@ -20,7 +20,7 @@
 .pkgenv <- new.env(parent=emptyenv())
 
 .defaultFile <- function() {
-    if (R.version.string >= "4.0.0") {
+    if (getRversion() >= "4.0.0") {
         tddir <- tools::R_user_dir("td")
         if (dir.exists(tddir)) {
             fname <- file.path(tddir, "api.dcf")
```

as

```
r> getRversion()
[1] ‘3.6.3’
> getRversion() >= "4.0.0"
[1] FALSE
> 
```

which is what I should have used.
