### ISSUE TITLE
Fundamental Statistics

### ISSUE THREAD

**Issue by krose** [eddelbuettel/td#5]
I'd like to add the [fundamental statistics](https://twelvedata.com/docs#statistics) end-point, if this is OK with you?

The data is pretty unruly, so I'm considering if it is best to return as "raw" only or maybe you have a better idea? Below is a `str()` of the data from the API.

```
List of 2
 $ ZIM:List of 5
  ..$ symbol           : chr "ZIM"
  ..$ name             : chr "ZIM Integrated Shipping Services Ltd."
  ..$ currency         : chr "USD"
  ..$ exchange         : chr "NYSE"
  ..$ exchange_timezone: chr "America/New_York"
 $ NA :List of 5
  ..$ valuations_metrics  :List of 9
  .. ..$ market_capitalization: num 8.13e+09
  .. ..$ enterprise_value     : num 7.76e+09
  .. ..$ trailing_pe          : num 2.45
  .. ..$ forward_pe           : num 3.6
  .. ..$ peg_ratio            : num -0.04
  .. ..$ price_to_sales_ttm   : num 0.943
  .. ..$ price_to_book_mrq    : num 2.57
  .. ..$ enterprise_to_revenue: num 0.9
  .. ..$ enterprise_to_ebitda : num 1.74
  ..$ financials          :List of 9
  .. ..$ fiscal_year_ends    : chr "2020-12-31"
  .. ..$ most_recent_quarter : chr "2021-09-30"
  .. ..$ profit_margin       : num 0.383
  .. ..$ operating_margin    : num 0.478
  .. ..$ return_on_assets_ttm: num 0.513
  .. ..$ return_on_equity_ttm: num 2.15
  .. ..$ income_statement    :List of 8
  .. .. ..$ revenue_ttm                  : num 8.62e+09
  .. .. ..$ revenue_per_share_ttm        : num 78.1
  .. .. ..$ quarterly_revenue_growth     : num 2.1
  .. .. ..$ gross_profit_ttm             : int 1156584000
  .. .. ..$ ebitda                       : num 4.46e+09
  .. .. ..$ net_income_to_common_ttm     : num 3.3e+09
  .. .. ..$ diluted_eps_ttm              : num 28
  .. .. ..$ quarterly_earnings_growth_yoy: num 9.26
  .. ..$ balance_sheet       :List of 7
  .. .. ..$ revenue_ttm             : num 8.62e+09
  .. .. ..$ total_cash_mrq          : num 2.8e+09
  .. .. ..$ total_cash_per_share_mrq: num 23.6
  .. .. ..$ total_debt_mrq          : num 2.8e+09
  .. .. ..$ total_debt_to_equity_mrq: num 88.2
  .. .. ..$ current_ratio_mrq       : num 1.58
  .. .. ..$ book_value_per_share_mrq: num 26.7
  .. ..$ cash_flow           :List of 2
  .. .. ..$ operating_cash_flow_ttm   : num 4.38e+09
  .. .. ..$ levered_free_cash_flow_ttm: num 2.52e+09
  ..$ stock_statistics    :List of 9
  .. ..$ shares_outstanding                 : int 118588000
  .. ..$ float_shares                       : int 80568815
  .. ..$ avg_10_volume                      : int 3953035
  .. ..$ avg_30_volume                      : int 3354837
  .. ..$ shares_short                       : int 3429041
  .. ..$ short_ratio                        : num 0.98
  .. ..$ short_percent_of_shares_outstanding: num 0.0484
  .. ..$ percent_held_by_insiders           : num 0.337
  .. ..$ percent_held_by_institutions       : num 0.451
  ..$ stock_price_summary :List of 6
  .. ..$ fifty_two_week_low   : num 14.2
  .. ..$ fifty_two_week_high  : num 69.8
  .. ..$ fifty_two_week_change: NULL
  .. ..$ beta                 : NULL
  .. ..$ day_50_ma            : num 56.5
  .. ..$ day_200_ma           : num 47.9
  ..$ dividends_and_splits:List of 10
  .. ..$ forward_annual_dividend_rate  : int 10
  .. ..$ forward_annual_dividend_yield : num 0.153
  .. ..$ trailing_annual_dividend_rate : num 2.5
  .. ..$ trailing_annual_dividend_yield: num 0.0375
  .. ..$ 5_year_average_dividend_yield : NULL
  .. ..$ payout_ratio                  : int 0
  .. ..$ dividend_date                 : chr "2021-12-27"
  .. ..$ ex_dividend_date              : chr "2021-12-15"
  .. ..$ last_split_factor             : NULL
  .. ..$ last_split_date               : NULL
 - attr(*, "accessed")= chr "2022-02-02 10:05:57"
```

**Comment by eddelbuettel** [comment]
Adding it even if 'incomplete or raw' is good and better than not having.  Please go for it, your last PR was nice.  We can even do it in stages.  

I presume you saw I did a quick 0.0.6 when new tests at CRAN found one comparison to improve?  So we have time to test and a prepare a 0.0.7 with this.

**Comment by krose** [comment]
Yes. I made a new fork and bumped it to 0.0.6.1.

I've kept the param as, but it really doesn't do anything. Probably best to remove it completely?

**Comment by eddelbuettel** [comment]
Thumbs up on 0.0.6.1.

What parameter `as` ?  I am a little behind the curve here and (literally !!) snowed in.

**Comment by eddelbuettel** [comment]
Crikey, yes. Gas trading must be fun. Geopolitics, and my former country men (and former state premier and chancellor and token spokesperson for gazprom, shudder, ...) plus weather should keep you entertaining.  Many moons ago I looked after some risk models for NG and annualized vol (at a crude proxy, risk management not vol trading ;-) ) was 80% (as I recall) to maybe 30% (??) for CL.  Electricty is likely worse as there is of course still no storage...

As for `as` and `raw`:  Maybe just document that return is 'what it is' or what jsonlite or RcppSimdJson make of it?  Can we hope to normalise?  Do we intentionally 'step aside' and user process it but are happy to provide the (valuable !!) service of accessing it?

**Comment by krose** [comment]
Our initial margin on front German power Cal contracts (which is not even the most volatile) have jumped from roughly 25K EUR to 256K EUR for 1 MW (8760 hours) of base deliveries, in about a year, so it has been pretty crazy. We have been lucky though, but both big and small shops have been suffering a bit with margin calls on long term hedges. Since we only do prop it hasn't been much of a concern for us, since we just size trades differently. But I must admit, that it's pretty interesting :)

I lean towards the solution where we step aside and let the user munge the data. I'll make a new commit with the change.
