### ISSUE TITLE
Installation problemm, R version 4.1.2

### ISSUE THREAD

**Issue by mnvx** [eddelbuettel/td#8]
Thanks for the great project!

I try to follow the instructions from the readme, but have the following error:

```r
> library(td)
Error in library(td) : there is no package called ‘td’
```

Could you help me to resolve the problem?

**Comment by eddelbuettel** [comment]
That means you didn't install it, or (highly unlikely) installed it to a location your `library()` call does not consider.

Try doing `install.packages("td", type="source")` to overcome the fact that you are on an outdated R version less well served by CRAN.

**Comment by mnvx** [comment]
A lot of thanks for the fast response. The next problem was in setting the API key.

I did this after exploring the source codes.

```r
install.packages("td", type="source")
Sys.setenv("TWELVEDATA_API_KEY" = "my_apikey")
library(td)
data <- time_series("SPY", "5min", outputsize=500, as="xts")
```

Maybe it is a good idea to add non-obvious steps into the readme.

Thanks anyway
